#!/bin/bash
water=$(echo "$WATER" | tr water 01234)
stir=$(echo "$STIR" | tr stir 0123)

sum=$((5#$water + 4#$stir))

printf "%o" "$sum" | tr 01234567 bestchol
echo "obase=8; ibase=5; $(echo $WATER | tr 'water' '01234') + $(echo $STIR | tr 'stir.' '01234')" | bc | tr '01234567' 'bestchol'
